# Generated by Django 4.0.6 on 2022-07-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_dadospaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospaciente',
            name='altura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_hdl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_ldl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='colesterol_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='percentual_gordura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='percentual_musculo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dadospaciente',
            name='triglicerideos',
            field=models.IntegerField(),
        ),
    ]
